name: Terraform-CI

on:
  push:
    branches:
      - main

jobs:
  terraform:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Enviernment/Preprod

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform fmt
        run: terraform fmt

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply -auto-approve
        run: terraform apply -auto-approve
